# The URL the site will be built for
base_url = "https://jfs.sh"
title = "jfs.sh"
description = "The rambling and tinkering of a climbing cryptographer."
compile_sass = true
build_search_index = false
output_dir = "docs"

minify_html = false
generate_feed = false
feed_filename = "feed.xml"
taxonomies = [
    {name = "tags"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"         # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "Jan Ferdinand Sauer"
id = "jfs"
bio = "Climbing Cryptographer."
avatar = "img/jfs.png"

show_id = false
show_projects = true

# == Icons, you can choose at https://remixicon.com/
blog_icon = "pen-nib-fill"
projects_icon = "flask-fill"
home_icon = "user-3-fill"
rss_icon = "rss-fill"
toc_icon = "menu-2-fill"

# == Social media links
links = [
    {name = "GitHub", icon = "github-fill", url = "https://github.com/jan-ferdinand"},
    {name = "Email", icon = "mail-fill", url = "mailto:jf@jfs.sh"}
    # Your can add more links
]

# == Footer
footer_copyright_name = "Jan Ferdinand Sauer"
footer_copyright_year = "2022"
footer_custom = " "
footer_credits = false

# == Feed
feed_in_blog_section = true

# == Feature Switches
toc = true
blur_effect = true
back_to_top_button = false
progress_bar = true
cc_license = false
cc_license_statement = "© [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)"
outdate_warn = false
outdate_warn_days = 120
outdate_warn_text_before = "Note: This article was last updated "
outdate_warn_text_after = " days ago and may be out of date."

# == Comments & Tracking
comment = "none"
analytics = "none"
